require('basics')
require('plugins')
require('colors')
require('trouble-config')
require('telescope-config')
-- require('snap-config')
-- require('fzf-config')
require('treesitter-config')
require('gitsigns-config')
require('nvimtree-config')
require('lsp-config')
require('lualine-config')
